stages:
  - test
manylinux_test_py27_unit:
  stage: test
  script:
    - python $CI_PROJECT_DIR/test/manylinux/run-docker-test.py -e py27-unit
  tags:
    - docker-shell
manylinux_test_py35_unit:
  stage: test
  script:
    - python $CI_PROJECT_DIR/test/manylinux/run-docker-test.py -e py35-unit
  tags:
    - docker-shell
manylinux_test_py36:
  stage: test
  script:
    - python $CI_PROJECT_DIR/test/manylinux/run-docker-test.py -e py36-unit
  tags:
    - docker-shell
manylinux_test_lint:
  stage: test
  script:
    - python $CI_PROJECT_DIR/test/manylinux/run-docker-test.py -e py27-lint
  tags:
    - docker-shell
manylinux_docs:
  stage: test
  script:
    - python $CI_PROJECT_DIR/test/manylinux/run-docker-test.py -e docs
  tags:
    - docker-shell
