language: python
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27-unit
  - python: "3.5"
    env: TOX_ENV=py35-unit
  - python: "3.6"
    env: TOX_ENV=py36-unit
  - python: "2.7"
    env: TOX_ENV=py27-lint
  - python: "2.7"
    env: TOX_ENV=docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
